  version: '3'

  services:
    node:
      container_name: nodejs
      image: joeejr/nodejs
      build:
        context: .
      volumes:
        - ./:/usr/src/app
      ports: 
        - "3000:3000"
      tty: true
      networks: 
        - nginx-node
      depends_on:
        - db
    
    nginx:
      container_name: nginx
      build:
        context: ./nginx
      volumes:
        - ./nginx:/etc/nginx/conf.d
      ports: 
        - "8080:80"
      networks: 
        - nginx-node
      depends_on:
        - node

    db:
      build: ./build
      command: --innodb-use-native-aio=0
      container_name: mysql
      restart: always
      tty: true
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - type: bind
          source: ./mysql
          target: /var/lib/mysql
      networks: 
        - nginx-node
      ports:
        - "3306:3306"

  networks:
    nginx-node:
      driver: bridge